config {
  type: "operations",
  hasOutput: true,
  schema: "bl_rep",
}

CREATE OR REPLACE FUNCTION ${self()}(
  ip_mandt INT64, ip_periv STRING, ip_date DATE
) AS

((
    SELECT IF(
      COALESCE(LENGTH(Xkale), 0) + COALESCE(LENGTH(Xjabh), 0) = 0,
      'CASE3',
      IF(Xkale IS NOT NULL, 'CASE1', 'CASE2')
    )
    FROM
      ${ref("t009")}
    WHERE
      CAST(Mandt AS INT64) = Ip_Mandt
      AND Periv = Ip_Periv
))